### ISSUE TITLE
add a support for a templates (for managed KMS credentials in json)

### ISSUE THREAD

**Issue by gerbil** [AliyunContainerService/ack-secret-manager#15]
```
apiVersion: alibabacloud.com/v1alpha1
kind: ExternalSecret
metadata:
  name: db-creds
spec:
  data:
    - key: secretinkms
      name: creds
  template:
    stringData:
      db-password: <%= JSON.parse(data.creds).AccountPassword %>
      db-username: <%= JSON.parse(data.creds).AccountName %>
```
